<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">
<xsd:element name="ZRFC_BP_CONTACT_EQ1">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="IV_BP_PARENT" type="xsd:string"/>
<xsd:element name="IV_FIRST_NAME" type="xsd:string"/>
<xsd:element name="IV_LAST_NAME" type="xsd:string"/>
<xsd:element name="IV_BP_CATEGORY" type="xsd:string" minOccurs="0"/>
<xsd:element name="IV_GROUPING" type="xsd:string" minOccurs="0"/>
<xsd:element name="IV_BP_ROLE" type="xsd:string" minOccurs="0"/>
<xsd:element name="IV_STREET" type="xsd:string" minOccurs="0"/>
<xsd:element name="IV_HOUSE_NUMBER" type="xsd:string" minOccurs="0"/>
<xsd:element name="IV_POSTAL_CODE" type="xsd:string" minOccurs="0"/>
<xsd:element name="IV_CITY" type="xsd:string" minOccurs="0"/>
<xsd:element name="IV_COUNTRY" type="xsd:string" minOccurs="0"/>
<xsd:element name="IV_REGION" type="xsd:string" minOccurs="0"/>
<xsd:element name="IV_LANGUAGE" type="xsd:string" minOccurs="0"/>
<xsd:element name="IV_DATE_FROM" type="xsd:string" minOccurs="0"/>
<xsd:element name="IV_DATE_TO" type="xsd:string" minOccurs="0"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>