<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="urn:sap-com:document:sap:rfc:functions"
           targetNamespace="urn:sap-com:document:sap:rfc:functions"
           elementFormDefault="qualified">

  <xs:simpleType name="char1">
    <xs:restriction base="xs:string"><xs:maxLength value="1"/></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="char3">
    <xs:restriction base="xs:string"><xs:maxLength value="3"/></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="char4">
    <xs:restriction base="xs:string"><xs:maxLength value="4"/></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="char6">
    <xs:restriction base="xs:string"><xs:maxLength value="6"/></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="char10">
    <xs:restriction base="xs:string"><xs:maxLength value="10"/></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="char20">
    <xs:restriction base="xs:string"><xs:maxLength value="20"/></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="char30">
    <xs:restriction base="xs:string"><xs:maxLength value="30"/></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="char32">
    <xs:restriction base="xs:string"><xs:maxLength value="32"/></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="char40">
    <xs:restriction base="xs:string"><xs:maxLength value="40"/></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="char50">
    <xs:restriction base="xs:string"><xs:maxLength value="50"/></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="char60">
    <xs:restriction base="xs:string"><xs:maxLength value="60"/></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="char220">
    <xs:restriction base="xs:string"><xs:maxLength value="220"/></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="date10">
    <xs:restriction base="xs:string">
      <xs:maxLength value="10"/>
      <xs:pattern value="\d\d\d\d-\d\d-\d\d"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="lang">
    <xs:restriction base="xs:string"><xs:maxLength value="1"/></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="numeric3">
    <xs:restriction base="xs:string">
      <xs:maxLength value="3"/>
      <xs:pattern value="\d*"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="numeric6">
    <xs:restriction base="xs:string">
      <xs:maxLength value="6"/>
      <xs:pattern value="\d*"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>
