<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:saprion:cpi:contact:source" targetNamespace="urn:saprion:cpi:contact:source" elementFormDefault="qualified">
<xs:element name="Contact">
<xs:complexType>
<xs:sequence>
<xs:element name="BpParent" type="xs:string"/>
<xs:element name="FirstName" type="xs:string"/>
<xs:element name="LastName" type="xs:string"/>
<xs:element name="BpCategory" type="xs:string" minOccurs="0"/>
<xs:element name="Grouping" type="xs:string" minOccurs="0"/>
<xs:element name="BpRole" type="xs:string" minOccurs="0"/>
<xs:element name="Street" type="xs:string" minOccurs="0"/>
<xs:element name="HouseNumber" type="xs:string" minOccurs="0"/>
<xs:element name="PostalCode" type="xs:string" minOccurs="0"/>
<xs:element name="City" type="xs:string" minOccurs="0"/>
<xs:element name="Country" type="xs:string" minOccurs="0"/>
<xs:element name="Region" type="xs:string" minOccurs="0"/>
<xs:element name="Language" type="xs:string" minOccurs="0"/>
<xs:element name="DateFrom" type="xs:dateTime" minOccurs="0"/>
<xs:element name="DateTo" type="xs:dateTime" minOccurs="0"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>